const products = [
  { id: 1, title: "Burger", category: "Fast Food", price: 5.99, img: ""},
  { id: 2, title: "Pizza", category: "Fast Food", price: 8.99, img: ""},
  { id: 3, title: "Hot Dog", category: "Fast Food", price: 4.99, img: ""},
  { id: 4, title: "French Fries", category: "Fast Food", price: 3.99, img: ""},
  { id: 5, title: "Chicken Nuggets", category: "Fast Food", price: 6.99, img: ""},
  { id: 6, title: "Cheeseburger", category: "Fast Food", price: 6.49, img: ""},
  { id: 7, title: "Chicken Sandwich", category: "Fast Food", price: 7.49, img: ""},
  { id: 8, title: "Fish Sandwich", category: "Fast Food", price: 7.99, img: ""},
  { id: 9, title: "Taco", category: "Fast Food", price: 3.49, img: ""},
  { id: 10, title: "Burrito", category: "Fast Food", price: 6.99, img: ""},
  { id: 11, title: "Pineapple", category: "Fruit", price: 3.99, img: ""},
  { id: 12, title: "Apple", category: "Fruit", price: 1.49, img: ""},
  { id: 13, title: "Banana", category: "Fruit", price: 0.99, img: ""},
  { id: 14, title: "Orange", category: "Fruit", price: 1.29, img: ""},
  { id: 15, title: "Strawberry", category: "Fruit", price: 2.99, img: ""},
  { id: 16, title: "Grapes", category: "Fruit", price: 2.49, img: ""},
  { id: 17, title: "Mango", category: "Fruit", price: 2.99, img: ""},
  { id: 18, title: "Pear", category: "Fruit", price: 1.79, img: ""},
  { id: 19, title: "Blueberry", category: "Fruit", price: 3.49, img: ""},
  { id: 20, title: "Raspberry", category: "Fruit", price: 3.99, img: ""},
  { id: 21, title: "Lime", category: "Fruit", price: 0.89, img: ""},
  { id: 22, title: "Avocado", category: "Fruit", price: 2.99, img: ""},
  { id: 23, title: "Coconut", category: "Fruit", price: 4.49, img: ""},
  { id: 24, title: "Carrot", category: "Vegetable", price: 1.19, img: ""},
  { id: 25, title: "Tomato", category: "Vegetable", price: 1.39, img: ""},
  { id: 26, title: "Lettuce", category: "Vegetable", price: 1.79, img: ""},
  { id: 27, title: "Cucumber", category: "Vegetable", price: 1.59, img: ""},
  { id: 28, title: "Potato", category: "Vegetable", price: 0.99, img: ""},
  { id: 29, title: "Onion", category: "Vegetable", price: 1.29, img: ""},
  { id: 30, title: "Garlic", category: "Vegetable", price: 1.99, img: ""},
  { id: 31, title: "Spinach", category: "Vegetable", price: 2.29, img: ""},
  { id: 32, title: "Broccoli", category: "Vegetable", price: 2.99, img: ""},
  { id: 33, title: "Bell Pepper", category: "Vegetable", price: 2.49, img: ""},
  { id: 34, title: "Eggplant", category: "Vegetable", price: 2.19, img: ""},
  { id: 35, title: "Zucchini", category: "Vegetable", price: 1.89, img: ""},
  { id: 36, title: "Corn", category: "Vegetable", price: 1.59, img: ""},
  { id: 37, title: "Celery", category: "Vegetable", price: 1.99, img: ""},
  { id: 38, title: "Radish", category: "Vegetable", price: 1.49, img: ""},
  { id: 39, title: "Coca Cola", category: "Drink", price: 1.99, img: ""},
  { id: 40, title: "Pepsi", category: "Drink", price: 1.89, img: ""},
  { id: 41, title: "Orange Juice", category: "Drink", price: 2.49, img: ""},
  { id: 42, title: "Lemonade", category: "Drink", price: 2.29, img: ""},
  { id: 43, title: "Water", category: "Drink", price: 0.99, img: ""},
  { id: 44, title: "Sprite", category: "Drink", price: 1.89, img: ""},
  { id: 45, title: "Fanta", category: "Drink", price: 1.79, img: ""},
  { id: 46, title: "Iced Tea", category: "Drink", price: 2.19, img: ""},
  { id: 47, title: "Milk", category: "Drink", price: 1.59, img: ""},
  { id: 48, title: "Coffee", category: "Drink", price: 2.99, img: ""},
  { id: 49, title: "Energy Drink", category: "Drink", price: 3.49, img: ""},
  { id: 50, title: "Ginger Ale", category: "Drink", price: 1.69, img: ""},
]


export default { products };