const products = [
  { id: 1, title: "Burger", category: "Fast Food", price: 5.99, img: "/images/products-grocery/burger.jpg"},
  { id: 2, title: "Pizza", category: "Fast Food", price: 8.99, img: "/images/products-grocery/pizza.jpg"},
  { id: 3, title: "Hot Dog", category: "Fast Food", price: 4.99, img: "/images/products-grocery/hotdog.jpg"},
  { id: 4, title: "French Fries", category: "Fast Food", price: 3.99, img: "/images/products-grocery/frenchfries.jpg"},
  { id: 5, title: "Chicken Nuggets", category: "Fast Food", price: 6.99, img: "/images/products-grocery/chickennuggets.jpg"},
  { id: 6, title: "Cheese Burger", category: "Fast Food", price: 6.49, img: "/images/products-grocery/cheeseburger.jpg"},
  { id: 7, title: "Chicken Sandwich", category: "Fast Food", price: 7.49, img: "/images/products-grocery/chickensandwich.jpg"},
  { id: 8, title: "Fish Sandwich", category: "Fast Food", price: 7.99, img: "/images/products-grocery/fishsandwich.jpg"},
  { id: 9, title: "Taco", category: "Fast Food", price: 3.49, img: "/images/products-grocery/taco.jpg"},
  { id: 10, title: "Burrito", category: "Fast Food", price: 6.99, img: "/images/products-grocery/burrito.jpg"},
  { id: 11, title: "Pineapple", category: "Fruit", price: 3.99, img: "/images/products-grocery/pineapple.jpg"},
  { id: 12, title: "Apple", category: "Fruit", price: 1.49, img: "/images/products-grocery/apple.jpg"},
  { id: 13, title: "Banana", category: "Fruit", price: 0.99, img: "/images/products-grocery/banana.jpg"},
  { id: 14, title: "Orange", category: "Fruit", price: 1.29, img: "/images/products-grocery/orange.jpg"},
  { id: 15, title: "Strawberry", category: "Fruit", price: 2.99, img: "/images/products-grocery/strawberry.jpg"},
  { id: 16, title: "Grapes", category: "Fruit", price: 2.49, img: "/images/products-grocery/grapes.jpg"},
  { id: 17, title: "Mango", category: "Fruit", price: 2.99, img: "/images/products-grocery/mango.jpg"},
  { id: 18, title: "Pear", category: "Fruit", price: 1.79, img: "/images/products-grocery/pear.jpg"},
  { id: 19, title: "Blueberry", category: "Fruit", price: 3.49, img: "/images/products-grocery/blueberry.jpg"},
  { id: 20, title: "Raspberry", category: "Fruit", price: 3.99, img: "/images/products-grocery/raspberry.jpg"},
  { id: 21, title: "Lime", category: "Fruit", price: 0.89, img: "/images/products-grocery/lime.jpg"},
  { id: 22, title: "Avocado", category: "Fruit", price: 2.99, img: "/images/products-grocery/avocado.jpg"},
  { id: 23, title: "Coconut", category: "Fruit", price: 4.49, img: "/images/products-grocery/coconut.jpg"},
  { id: 24, title: "Carrot", category: "Vegetable", price: 1.19, img: "/images/products-grocery/carrot.jpg"},
  { id: 25, title: "Tomato", category: "Vegetable", price: 1.39, img: "/images/products-grocery/tomato.jpg"},
  { id: 26, title: "Lettuce", category: "Vegetable", price: 1.79, img: "/images/products-grocery/lettuce.jpg"},
  { id: 27, title: "Cucumber", category: "Vegetable", price: 1.59, img: "/images/products-grocery/cucumber.jpg"},
  { id: 28, title: "Potato", category: "Vegetable", price: 0.99, img: "/images/products-grocery/potato.jpg"},
  { id: 29, title: "Onion", category: "Vegetable", price: 1.29, img: "/images/products-grocery/onion.jpg"},
  { id: 30, title: "Garlic", category: "Vegetable", price: 1.99, img: "/images/products-grocery/garlic.jpg"},
  { id: 31, title: "Spinach", category: "Vegetable", price: 2.29, img: "/images/products-grocery/spinach.jpg"},
  { id: 32, title: "Broccoli", category: "Vegetable", price: 2.99, img: "/images/products-grocery/broccoli.jpg"},
  { id: 33, title: "Bell Pepper", category: "Vegetable", price: 2.49, img: "/images/products-grocery/bellpepper.jpg"},
  { id: 34, title: "Eggplant", category: "Vegetable", price: 2.19, img: "/images/products-grocery/eggplant.jpg"},
  { id: 35, title: "Zucchini", category: "Vegetable", price: 1.89, img: "/images/products-grocery/zucchini.jpg"},
  { id: 36, title: "Corn", category: "Vegetable", price: 1.59, img: "/images/products-grocery/corn.jpg"},
  { id: 37, title: "Celery", category: "Vegetable", price: 1.99, img: "/images/products-grocery/celery.jpg"},
  { id: 38, title: "Radish", category: "Vegetable", price: 1.49, img: "/images/products-grocery/radish.jpg"},
  { id: 39, title: "Coca Cola", category: "Drink", price: 1.99, img: "/images/products-grocery/cocacola.jpg"},
  { id: 40, title: "Pepsi", category: "Drink", price: 1.89, img: "/images/products-grocery/pepsi.jpg"},
  { id: 41, title: "Orange Juice", category: "Drink", price: 2.49, img: "/images/products-grocery/orangejuice.jpg"},
  { id: 42, title: "Lemonade", category: "Drink", price: 2.29, img: "/images/products-grocery/lemonade.jpg"},
  { id: 43, title: "Water", category: "Drink", price: 0.99, img: "/images/products-grocery/water.jpg"},
  { id: 44, title: "Sprite", category: "Drink", price: 1.89, img: "/images/products-grocery/sprite.jpg"},
  { id: 45, title: "Fanta", category: "Drink", price: 1.79, img: "/images/products-grocery/fanta.jpg"},
  { id: 46, title: "Iced Tea", category: "Drink", price: 2.19, img: "/images/products-grocery/icedtea.jpg"},
  { id: 47, title: "Milk", category: "Drink", price: 1.59, img: "/images/products-grocery/milk.jpg"},
  { id: 48, title: "Coffee", category: "Drink", price: 2.99, img: "/images/products-grocery/coffee.jpg"},
  { id: 49, title: "Energy Drink", category: "Drink", price: 3.49, img: "/images/products-grocery/energydrink.jpg"},
  { id: 50, title: "Ginger Ale", category: "Drink", price: 1.69, img: "/images/products-grocery/gingerale.jpg"},
]


export default { products };